# Generated by Django 5.2.6 on 2025-10-03 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cliente',
            table=None,
        ),
    ]
