# Generated by Django 5.2.6 on 2025-10-08 08:13

import django.db.models.deletion
import store.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_cliente_tipo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='apellidos',
            field=models.CharField(max_length=150, validators=[store.validators.validate_name]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(max_length=100, unique=True, validators=[store.validators.validate_email_extended]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=100, validators=[store.validators.validate_name]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(max_length=9, validators=[store.validators.validate_chilean_phone]),
        ),
        migrations.CreateModel(
            name='ImagenProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='productos/adicionales/')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de visualización de la imagen')),
                ('descripcion', models.CharField(blank=True, help_text='Descripción opcional de la imagen', max_length=200, null=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes_adicionales', to='store.producto')),
            ],
            options={
                'verbose_name': 'Imagen adicional del producto',
                'verbose_name_plural': 'Imágenes adicionales del producto',
                'ordering': ['orden', 'fecha_subida'],
            },
        ),
    ]
