# Generated by Django 5.2.6 on 2025-10-08 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_cliente_apellidos_alter_cliente_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenproducto',
            name='orden',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
