# Generated by Django 5.2.6 on 2025-10-27 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_transaccionwebpay'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransaccionMercadoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference_id', models.CharField(help_text='ID de preferencia de MercadoPago', max_length=255, unique=True)),
                ('payment_id', models.CharField(blank=True, help_text='ID del pago confirmado', max_length=255, null=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('authorized', 'Autorizado'), ('in_process', 'En Proceso'), ('in_mediation', 'En Mediación'), ('rejected', 'Rechazado'), ('cancelled', 'Cancelado'), ('refunded', 'Reembolsado'), ('charged_back', 'Contracargo')], default='pending', max_length=20)),
                ('status_detail', models.CharField(blank=True, help_text='Detalle del estado', max_length=100, null=True)),
                ('payment_method_id', models.CharField(blank=True, help_text='Método de pago', max_length=50, null=True)),
                ('payment_type_id', models.CharField(blank=True, help_text='Tipo de pago', max_length=50, null=True)),
                ('card_last_four_digits', models.CharField(blank=True, help_text='Últimos 4 dígitos', max_length=4, null=True)),
                ('payer_email', models.EmailField(blank=True, help_text='Email del pagador', max_length=254, null=True)),
                ('payer_identification', models.CharField(blank=True, help_text='Identificación', max_length=50, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, help_text='Fecha de aprobación', null=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones_mercadopago', to='store.pedido')),
            ],
            options={
                'verbose_name': 'Transacción Mercado Pago',
                'verbose_name_plural': 'Transacciones Mercado Pago',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
