# Generated by Django 5.2.6 on 2025-11-09 02:13

import django.db.models.deletion
import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_transaccionmercadopago'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoTransferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario_usuario', models.TextField(blank=True, help_text='Comentario dejado por el cliente', null=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Revisión'), ('APROBADO', 'Pago Aprobado'), ('RECHAZADO', 'Pago Rechazado')], default='PENDIENTE', max_length=20)),
                ('fecha_revision', models.DateTimeField(blank=True, null=True)),
                ('comentario_admin', models.TextField(blank=True, help_text='Comentario interno del administrador', null=True)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pago_transferencia', to='store.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='ComprobanteTransferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to=store.models.transferencia_upload_path)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comprobantes', to='store.pagotransferencia')),
            ],
        ),
    ]
