# Generated by Django 5.2.6 on 2025-12-07 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_tag_producto_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='marca',
            name='es_marca_auto',
            field=models.BooleanField(default=False, help_text='Marcar si esta marca corresponde a un fabricante de vehículos (ej: Nissan, Toyota).', verbose_name='Es Marca de Auto'),
        ),
    ]
