from django.contrib import admin
from django.urls import path
from store.views import (
    home, 
    contacto, 
    about, 
    seguimiento_compra, 
    centro_ayuda, 
    garantias, 
    politicas_privacidad, 
    terminos_condiciones,
    product_detail,
    add_to_cart,
    view_cart,
    update_cart,
    remove_from_cart,
    radios_catalog,
    product_catalog,
    login_view, 
    register_view,
    logout_view,
    panel_gestion_view,
    listar_productos_view,
    crear_producto_view,
    editar_producto_view,
    eliminar_producto_view,
    listar_categorias_view,
    crear_categoria_view,
    editar_categoria_view,
    eliminar_categoria_view,
    listar_marcas_view,
    crear_marca_view,
    editar_marca_view,
    eliminar_marca_view,
    exportar_productos_csv,
    exportar_categorias_csv,
    exportar_marcas_csv
)

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'), 
    path('contacto/', contacto, name='contacto'), 
    path('quienes-somos/', about, name='about'),
    path('seguimiento-compra/', seguimiento_compra, name='seguimiento_compra'),
    path('centro-ayuda/', centro_ayuda, name='centro_ayuda'),
    path('garantias/', garantias, name='garantias'),
    path('politicas-privacidad/', politicas_privacidad, name='politicas_privacidad'),
    path('terminos-condiciones/', terminos_condiciones, name='terminos_condiciones'),
    path('tienda/', product_catalog, name='product_catalog'),
    path('tienda/marca/<str:brand_name>/', product_catalog, name='product_catalog_by_brand'),
    path('radios/', radios_catalog, name='radios_catalog'),
    path('producto/<int:product_id>/', product_detail, name='product_detail'),
    path('carro/', view_cart, name='view_cart'),
    path('agregar/<int:product_id>/', add_to_cart, name='add_to_cart'),
    path('actualizar-carro/<int:product_id>/', update_cart, name='update_cart'),
    path('eliminar-del-carro/<int:product_id>/', remove_from_cart, name='remove_from_cart'),
    path('login/', login_view, name='login'),
    path('registro/', register_view, name='register'),
    path('logout/', logout_view, name='logout'), 
    path('gestion/', panel_gestion_view, name='panel_gestion'),
    path('gestion/productos/', listar_productos_view, name='listar_productos'),
    path('gestion/productos/crear/', crear_producto_view, name='crear_producto'),
    path('gestion/productos/editar/<int:pk>/', editar_producto_view, name='editar_producto'),
    path('gestion/productos/eliminar/<int:pk>/', eliminar_producto_view, name='eliminar_producto'),
    path('gestion/productos/exportar-csv/', exportar_productos_csv, name='exportar_productos_csv'), 
    path('gestion/categorias/', listar_categorias_view, name='listar_categorias'),
    path('gestion/categorias/crear/', crear_categoria_view, name='crear_categoria'),
    path('gestion/categorias/editar/<int:pk>/', editar_categoria_view, name='editar_categoria'),
    path('gestion/categorias/eliminar/<int:pk>/', eliminar_categoria_view, name='eliminar_categoria'),
    path('gestion/categorias/exportar-csv/', exportar_categorias_csv, name='exportar_categorias_csv'),
    path('gestion/marcas/exportar-csv/', exportar_marcas_csv, name='exportar_marcas_csv'),
    path('gestion/marcas/', listar_marcas_view, name='listar_marcas'),
    path('gestion/marcas/crear/', crear_marca_view, name='crear_marca'),
    path('gestion/marcas/editar/<int:pk>/', editar_marca_view, name='editar_marca'),
    path('gestion/marcas/eliminar/<int:pk>/', eliminar_marca_view, name='eliminar_marca'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)