from django.contrib import admin
from django.urls import path
from store import views
import techtop_project.settings as settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'), 
    path('contacto/', views.contacto, name='contacto'), 
    path('quienes-somos/', views.about, name='about'),
    path('seguimiento-compra/', views.seguimiento_compra, name='seguimiento_compra'),
    path('centro-ayuda/', views.centro_ayuda, name='centro_ayuda'),
    path('garantias/', views.garantias, name='garantias'),
    path('politicas-privacidad/', views.politicas_privacidad, name='politicas_privacidad'),
    path('terminos-condiciones/', views.terminos_condiciones, name='terminos_condiciones'),
    path('tienda/', views.product_catalog, name='product_catalog'),
    path('tienda/marca/<str:brand_name>/', views.product_catalog, name='product_catalog_by_brand'),
    path('radios/', views.radios_catalog, name='radios_catalog'),
    path('electronica/', views.electronica_catalog, name='electronica_catalog'),
    path('api/get-cart/', views.get_cart_data, name='get_cart_data'),
    path('accesorios/', views.accesorios_catalog, name='accesorios_catalog'),
    path('categoria/<str:categoria_nombre>/', views.category_catalog, name='category_catalog'),
    path('producto/<int:product_id>/', views.product_detail, name='product_detail'),
    path('carro/', views.view_cart, name='view_cart'),
    path('agregar/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('actualizar-carro/<int:product_id>/', views.update_cart, name='update_cart'),
    path('eliminar-del-carro/<int:product_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('login/', views.login_view, name='login'),
    path('registro/', views.register_view, name='register'),
    path('logout/', views.logout_view, name='logout'), 
    path('buscar/', views.search_results_view, name='search'),
    path('gestion/', views.panel_gestion_view, name='panel_gestion'),
    path('gestion/productos/', views.listar_productos_view, name='listar_productos'),
    path('gestion/productos/crear/', views.crear_producto_view, name='crear_producto'),
    path('gestion/productos/editar/<int:pk>/', views.editar_producto_view, name='editar_producto'),
    path('gestion/productos/eliminar/<int:pk>/', views.eliminar_producto_view, name='eliminar_producto'),
    path('gestion/productos/exportar-csv/', views.exportar_productos_csv, name='exportar_productos_csv'), 
    path('gestion/categorias/', views.listar_categorias_view, name='listar_categorias'),
    path('gestion/categorias/crear/', views.crear_categoria_view, name='crear_categoria'),
    path('gestion/categorias/editar/<int:pk>/', views.editar_categoria_view, name='editar_categoria'),
    path('gestion/categorias/eliminar/<int:pk>/', views.eliminar_categoria_view, name='eliminar_categoria'),
    path('gestion/categorias/exportar-csv/', views.exportar_categorias_csv, name='exportar_categorias_csv'),
    path('gestion/marcas/', views.listar_marcas_view, name='listar_marcas'),
    path('gestion/marcas/crear/', views.crear_marca_view, name='crear_marca'),
    path('gestion/marcas/editar/<int:pk>/', views.editar_marca_view, name='editar_marca'),
    path('gestion/marcas/eliminar/<int:pk>/', views.eliminar_marca_view, name='eliminar_marca'),
    path('gestion/marcas/exportar-csv/', views.exportar_marcas_csv, name='exportar_marcas_csv'),
]

